Repository recurly/recurly-client-dotnet, pull requests merged in 2019-06, with the labels that each got.

#408 Latest v2018-08-09 Updates
  Recurly/Client.cs
  Recurly/Resources/CustomFieldDefinition.cs
  Recurly/Resources/Transaction.cs
Labels: V3

#409 Bump to 3.0.0-beta.4
  README.md
  Recurly/Recurly.csproj
Labels: V3

#410 Update pagination doc
  README.md
  Recurly.Tests/PagerTest.cs
Labels: V3

#412 Remove dep scripts from readme
  README.md
Labels: V3

#414 Allow programmer to change the PlanCode
  Library/Plan.cs
Labels: bug

#407 Make Error parsing more robust and support STRICT_MODE
  Recurly/Errors/ApiErrors.cs
  Recurly/Utils.cs
  scripts/test
Labels: V3

#415 Add 3DS tokens to transaction error and billing info
  Library/BillingInfo.cs
  Library/TransactionError.cs
  Library/TransactionErrorEnum.cs
Labels: new feature

#424 Latest v2018-08-09 Changes
  Recurly/Client.cs
  Recurly/Resources/AccountPurchase.cs
  Recurly/Resources/CustomFieldDefinition.cs
  Recurly/Resources/PurchaseCreate.cs
  Recurly/Resources/SubscriptionPurchase.cs
  Recurly/Resources/SubscriptionShippingPurchase.cs
Labels: V3

#425 3.0.0.beta.5
  README.md
  Recurly/Recurly.csproj
Labels: V3
