Repository recurly/recurly-client-dotnet, pull requests merged in 2019-12, with the labels that each got.

#469 Release 3.2.0
  .bumpversion.cfg
  Recurly/Recurly.csproj
Labels: V3

#470 Synchronize latest V3 Changes
  .bumpversion.cfg
  Recurly/Recurly.csproj
  Recurly/Resources/LineItemCreate.cs
  Recurly/Resources/PurchaseCreate.cs
  Recurly/Resources/ShippingAddress.cs
  openapi/api.yaml
Labels: V3, enhancement

#472 Update History.md
  History.md
Labels: V2
