Repository recurly/recurly-client-dotnet, pull requests merged in 2020-08, with the labels that each got.

#559 Account for when usage_percentage is null
  Library/AddOn.cs
Labels: V2

#562 Convert float to decimal
  Recurly.Tests/Fixtures.cs
  Recurly.Tests/JsonSerializerTest.cs
  Recurly.Tests/UtilsTest.cs
  Recurly/Resources/AccountAcquisitionCost.cs
  Recurly/Resources/AccountBalanceAmount.cs
  Recurly/Resources/AddOn.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/AddOnMini.cs
  Recurly/Resources/AddOnUpdate.cs
  Recurly/Resources/CouponDiscountPricing.cs
  Recurly/Resources/CouponPricing.cs
  Recurly/Resources/CouponRedemption.cs
  Recurly/Resources/CouponRedemptionMini.cs
  Recurly/Resources/CreditPayment.cs
  Recurly/Resources/ExternalTransaction.cs
  Recurly/Resources/Invoice.cs
  Recurly/Resources/InvoiceRefund.cs
  Recurly/Resources/LineItem.cs
  Recurly/Resources/LineItemCreate.cs
  Recurly/Resources/PlanPricing.cs
  Recurly/Resources/Pricing.cs
  Recurly/Resources/ShippingFeeCreate.cs
  Recurly/Resources/Subscription.cs
  Recurly/Resources/SubscriptionAddOn.cs
  Recurly/Resources/SubscriptionAddOnCreate.cs
  Recurly/Resources/SubscriptionAddOnTier.cs
  Recurly/Resources/SubscriptionAddOnUpdate.cs
  Recurly/Resources/SubscriptionChange.cs
  Recurly/Resources/SubscriptionChangeCreate.cs
  Recurly/Resources/SubscriptionChangeShippingCreate.cs
  Recurly/Resources/SubscriptionCreate.cs
  Recurly/Resources/SubscriptionPurchase.cs
  Recurly/Resources/SubscriptionShipping.cs
  Recurly/Resources/SubscriptionShippingCreate.cs
  Recurly/Resources/SubscriptionShippingPurchase.cs
  Recurly/Resources/TaxInfo.cs
  Recurly/Resources/Transaction.cs
  Recurly/Resources/Usage.cs
  Recurly/Resources/UsageCreate.cs
Labels: enhancement

#563 Add tax identifier fields to billing info
  Library/BillingInfo.cs
Labels: V2

#565 Return EmptyResource
  Recurly/Client.cs
  Recurly/IClient.cs
Labels: enhancement

#564 Apply level of abstraction to xml writers by using WriteStringIfValid()
  Library/BillingInfo.cs
Labels: V2

#566 Write xml for address2 field as long as it is not null
  Library/BillingInfo.cs
Labels: V2

#560 Client Event Handlers
  Recurly.Tests/BaseClientTest.cs
  Recurly/BaseClient.cs
  Recurly/Errors/ApiErrors.cs
  Recurly/Http.cs
  Recurly/IEventHandler.cs
  scripts/format
Labels: new feature

#567 Release 1.17.7
  History.md
  Library/BillingInfo.cs
  Library/Configuration/Settings.cs
  Library/Properties/AssemblyInfo.cs
  dist/recurly.nuspec
Labels: V2

#568 Fri Aug 21 16:21:53 UTC 2020 Upgrade API version v2019-10-10
  Recurly/Client.cs
  Recurly/Errors/ApiErrors.cs
  Recurly/IClient.cs
  Recurly/Resources/AddOn.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/AddOnUpdate.cs
  Recurly/Resources/Item.cs
  Recurly/Resources/ItemCreate.cs
  Recurly/Resources/ItemUpdate.cs
  Recurly/Resources/LineItem.cs
  Recurly/Resources/LineItemCreate.cs
  Recurly/Resources/Plan.cs
  Recurly/Resources/PlanCreate.cs
  Recurly/Resources/PlanUpdate.cs
  Recurly/Resources/ShippingPurchase.cs
  Recurly/Resources/SubscriptionChangeCreate.cs
  openapi/api.yaml
Labels: enhancement

#573 Mon Aug 31 19:45:47 UTC 2020 Upgrade API version v2019-10-10
  Recurly/Resources/CouponCreate.cs
  Recurly/Resources/SubscriptionChange.cs
  Recurly/Resources/SubscriptionChangeCreate.cs
  Recurly/Resources/SubscriptionChangePreview.cs
  openapi/api.yaml
Labels: enhancement

#572 Code of Conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation
