Repository recurly/recurly-client-dotnet, pull requests merged in 2020-06, with the labels that each got.

#519 Setting Next in Pager.Build to fix async pager requests
  Recurly/Pager.cs
Labels: bug

#517 Updating internal scripts to use globally installed dotnet-format
  scripts/build
  scripts/format
Labels: enhancement

#521 Applying query params to url before creating the request
  Recurly.Tests/BaseClientTest.cs
  Recurly/BaseClient.cs
Labels: bug

#526 Document a way to handle webhooks
  README.md
Labels: documentation

#515 Update serializer for item-backed add-ons to accommodate QBP
  Library/AddOn.cs
  Test/AddOnTest.cs
Labels: V2

#524 Adding RequestOptions to facilitate passing custom request headers
  Recurly.Tests/BaseClientTest.cs
  Recurly.Tests/MockClient.cs
  Recurly.Tests/PagerTest.cs
  Recurly.Tests/RequestOptionsTest.cs
  Recurly/BaseClient.cs
  Recurly/Client.cs
  Recurly/Pager.cs
  Recurly/RequestOptions.cs
Labels: new feature

#525 Add timeframe query params to cancel subscription endpoint
  Library/Subscription.cs
  Test/SubscriptionTest.cs
Labels: V2, enhancement

#532 Fixing query parameter handling in the Pager class
  Recurly.Tests/PagerTest.cs
  Recurly/BaseClient.cs
  Recurly/Pager.cs
Labels: bug

#529 Repair test to expect a validation exception
  Test/BillingInfoTest.cs
Labels: V2

#530 Expect validation exception when converting trial with fake token
  Test/SubscriptionTest.cs
Labels: V2

#543 Merge v2.27 features into v2 branch for release
  Library/BillingInfo.cs
  Library/Configuration/Settings.cs
  Library/List/SubscriptionAddOnList.cs
  Library/Plan.cs
  Library/SubscriptionAddOn.cs
  Test/BillingInfoTest.cs
  Test/List/SubscriptionAddOnListTest.cs
Labels: V2

#544 Release 1.17.5
  History.md
  Library/Properties/AssemblyInfo.cs
  dist/recurly.nuspec
Labels: V2
