Repository recurly/recurly-client-dotnet, pull requests merged in 2020-11, with the labels that each got.

#589 Latest Changes for 2019-10-10 (Wallet, Item Coupons)
  Recurly/Client.cs
  Recurly/Errors/ApiErrors.cs
  Recurly/Errors/Factory.cs
  Recurly/IClient.cs
  Recurly/Resources/BillingInfo.cs
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/Coupon.cs
  Recurly/Resources/CouponCreate.cs
  Recurly/Resources/Invoice.cs
  Recurly/Resources/InvoiceCollect.cs
  Recurly/Resources/Subscription.cs
  Recurly/Resources/SubscriptionUpdate.cs
  openapi/api.yaml
Labels: enhancement

#588 Support item-specific coupons
  Library/Coupon.cs
  Test/CouponTest.cs
Labels: V2

#590 Release 1.17.9
  History.md
  Library/Properties/AssemblyInfo.cs
  dist/recurly.nuspec
Labels: V2

#592 Fix test: create billing info (IBAN)
  Test/BillingInfoTest.cs
Labels: V2

#593 Expose fields in response xml to developer
  Library/AddOn.cs
  Library/BillingInfo.cs
Labels: V2

#594 Latest Changes for 2019-10-10
  Recurly/Client.cs
  Recurly/IClient.cs
  Recurly/Resources/Subscription.cs
  openapi/api.yaml
Labels: enhancement

#595 Update readme to include memo on headers
  README.md
Labels: V3, documentation

#597 Latest Changes for 2019-10-10 (tax_identifier / tax_identifier_type)
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/PlanUpdate.cs
  openapi/api.yaml
Labels: enhancement
