Repository recurly/recurly-client-dotnet, pull requests merged in 2021-11, with the labels that each got.

#670 Update to properly encode query string parameters
  Recurly.Tests/BaseClientTest.cs
  Recurly.Tests/UtilsTest.cs
  Recurly/Utils.cs
Labels: bug, V4

#672 Generated Latest Changes for v2019-10-10 (Account Hierarchy Invoice Rollup)
  Recurly/Resources/LineItem.cs
  openapi/api.yaml
Labels: V3

#673 Generated Latest Changes for v2021-02-25
  Recurly/Constants.cs
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/LineItem.cs
  openapi/api.yaml
Labels: V4
