Repository recurly/recurly-client-dotnet, pull requests merged in 2021-04, with the labels that each got.

#625 Generated Latest Changes for v2021-02-25
  Recurly/Resources/BillingInfoCreate.cs
  openapi/api.yaml
Labels: V4

#627 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: V4, internal

#630 Updating release script to be more defensive
  scripts/release
Labels: V4, internal

#629 Adding release scripts
  .bumpversion.cfg
  .changelog_config.yaml
  CHANGELOG.md
  scripts/prepare-release
Labels: V2, internal

#628 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: V3, internal

#631 Generated Latest Changes for v2021-02-25 (Backup Payment Method)
  Recurly/Resources/BillingInfo.cs
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/SubscriptionPurchase.cs
  Recurly/Resources/Transaction.cs
  openapi/api.yaml
Labels: V4

#632 Removing NUGET_TOKEN from release script in favor of system config
  scripts/release
Labels: V3, internal

#626 Wallet and Backup Payment
  Library/Account.cs
  Library/AddOn.cs
  Library/BillingInfo.cs
  Library/Invoice.cs
  Library/List/BillingInfoList.cs
  Library/Purchase.cs
  Library/Recurly.csproj
  Library/Subscription.cs
  Library/SubscriptionChange.cs
  Test/AccountTest.cs
  Test/BaseTest.cs
  Test/BillingInfoTest.cs
  Test/SubscriptionTest.cs
Labels: V2

#634 Generated Latest Changes for v2021-02-25
  Recurly/Resources/SubscriptionAddOnTier.cs
  openapi/api.yaml
Labels: V4

#635 Updating release script to use 'dotnet nuget'
  scripts/release
Labels: V2, internal

#637 Updating release script
  scripts/release
Labels: V3, internal

#636 Updating release script
  scripts/release
Labels: V4, internal
