Repository recurly/recurly-client-dotnet, pull requests merged in 2022-08, with the labels that each got.

#719 Adding github actions
  .github/workflows/ci.yml
  .travis.yml
  Test/InvoiceTest.cs
  Test/List/InvoiceListTest.cs
  scripts/test
Labels: V2, internal

#720 Added Support for Ramp Pricing Feature
  Library/Plan.cs
  Library/PlanRampInterval.cs
  Library/PlanRampPricing.cs
  Library/PricingModelType.cs
  Test/BaseTest.cs
  Test/List/PlanListTest.cs
  Test/PlanTest.cs
Labels: new feature, V2

#722 Added Support for Ramp Intervals on a Subscription
  Library/Plan.cs
  Library/Subscription.cs
  Library/SubscriptionChange.cs
  Library/SubscriptionRampInterval.cs
  Test/BaseTest.cs
  Test/List/PlanListTest.cs
  Test/List/SubscriptionListTest.cs
  Test/PlanTest.cs
  Test/SubscriptionTest.cs
Labels: V2

#724 Add Unit Tests for Purchases with Ramp Pricing
  Test/BaseTest.cs
  Test/PurchaseTest.cs
Labels: V2

#726 Fixes bug with PutDunningCampaignBulkUpdate
  Recurly/Client.cs
  Recurly/IClient.cs
  openapi/api.yaml
Labels: bug, V4

#729 Updating release script to work properly
  .bumpversion.cfg
  Library/Recurly.csproj
  scripts/release
Labels: V2, internal

#731 fix styling issues
  Library/BillingInfo.cs
  Library/VerifyBillingInfoCvv.cs
  Test/BillingInfoTest.cs
Labels: V2
