Repository recurly/recurly-client-dotnet, pull requests merged in 2022-10, with the labels that each got.

#739 Generated Latest Changes for v2019-10-10(Decimal Usage and Quantities)
  Recurly/Client.cs
  Recurly/IClient.cs
  Recurly/Resources/LineItem.cs
  Recurly/Resources/LineItemRefund.cs
  Recurly/Resources/PlanRampInterval.cs
  Recurly/Resources/SubscriptionRampInterval.cs
  Recurly/Resources/SubscriptionRampIntervalResponse.cs
  Recurly/Resources/Usage.cs
  Recurly/Resources/UsageCreate.cs
  openapi/api.yaml
Labels: V3

#740 Generated Latest Changes for v2021-02-25(Decimal Usage and Quantities and DunningEvent new fields)
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/Invoice.cs
  Recurly/Resources/LineItem.cs
  Recurly/Resources/LineItemRefund.cs
  Recurly/Resources/Usage.cs
  Recurly/Resources/UsageCreate.cs
  openapi/api.yaml
Labels: V4

#743 Generated Latest Changes for v2021-02-25 (Entitlements feature)
  Recurly/Client.cs
  Recurly/Constants.cs
  Recurly/IClient.cs
  Recurly/Resources/CustomerPermission.cs
  Recurly/Resources/Entitlement.cs
  Recurly/Resources/Entitlements.cs
  Recurly/Resources/GrantedBy.cs
  Recurly/Resources/ListEntitlementsParams.cs
  openapi/api.yaml
Labels: V4

#735 adds support for entitlements
  Library/Account.cs
  Library/CustomerPermission.cs
  Library/Entitlement.cs
  Library/List/EntitlementList.cs
  Test/List/EntitlementListTest.cs
Labels: new feature, V2
