Repository recurly/recurly-client-dotnet, pull requests merged in 2022-04, with the labels that each got.

#699 Generated Latest Changes for v2019-10-10
  Recurly/Resources/Subscription.cs
  openapi/api.yaml
Labels: V3

#700 Generated Latest Changes for v2021-02-25
  Recurly/Constants.cs
  Recurly/Resources/AddOn.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/Subscription.cs
  Recurly/Resources/SubscriptionAddOn.cs
  openapi/api.yaml
Labels: V4

#701 Adding actions
  .github/workflows/ci.yml
  .travis.yml
Labels: V4, internal

#703 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
Labels: V3, internal
