Repository recurly/recurly-client-dotnet, pull requests merged in 2022-11, with the labels that each got.

#746 Generated Latest Changes for v2019-10-10
  Recurly/Client.cs
  Recurly/IClient.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/Plan.cs
  Recurly/Resources/PlanCreate.cs
  Recurly/Resources/PlanUpdate.cs
  Recurly/Resources/SubscriptionAddOnCreate.cs
  openapi/api.yaml
Labels: V3

#747 Generated Latest Changes for v2021-02-25
  Recurly/Client.cs
  Recurly/Constants.cs
  Recurly/IClient.cs
  Recurly/Resources/AddOn.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/Plan.cs
  Recurly/Resources/PlanCreate.cs
  Recurly/Resources/PlanUpdate.cs
  Recurly/Resources/SubscriptionAddOn.cs
  Recurly/Resources/SubscriptionAddOnCreate.cs
  Recurly/Resources/Usage.cs
  openapi/api.yaml
Labels: V4

#748 Generated Latest Changes for v2021-02-25 (External Subscriptions feature)
  Recurly/Client.cs
  Recurly/Constants.cs
  Recurly/IClient.cs
  Recurly/Resources/AddOn.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/AddOnUpdate.cs
  Recurly/Resources/ExternalProduct.cs
  Recurly/Resources/ExternalProductReferenceMini.cs
  Recurly/Resources/ExternalResourceMini.cs
  Recurly/Resources/ExternalSubscription.cs
  Recurly/Resources/ListAccountExternalSubscriptionsParams.cs
  Recurly/Resources/ListExternalProductsParams.cs
  Recurly/Resources/ListExternalSubscriptionsParams.cs
  Recurly/Resources/SubscriptionAddOn.cs
  openapi/api.yaml
Labels: V4

#752 Generated Latest Changes for v2019-10-10 (Apply Credit Balance feature)
  Recurly/Client.cs
  Recurly/IClient.cs
  Recurly/Resources/AccountBalanceAmount.cs
  openapi/api.yaml
Labels: V3

#753 Generated Latest Changes for v2021-02-25 (Apply Credit Balance feature)
  Recurly/Client.cs
  Recurly/Constants.cs
  Recurly/IClient.cs
  Recurly/Resources/AccountBalanceAmount.cs
  openapi/api.yaml
Labels: V4

#754 V2 add support for Apply Credit Balance to existing invoice feature
  Library/AccountBalance.cs
  Library/Invoice.cs
  Test/AccountTest.cs
  Test/InvoiceTest.cs
Labels: V2
