Repository recurly/recurly-client-dotnet, pull requests merged in 2023-01, with the labels that each got.

#756 Generated Latest Changes for v2019-10-10 (Account Preferred Time Zone)
  Recurly/Resources/Account.cs
  Recurly/Resources/AccountCreate.cs
  Recurly/Resources/AccountPurchase.cs
  Recurly/Resources/AccountUpdate.cs
  Recurly/Resources/Invoice.cs
  openapi/api.yaml
Labels: V3

#757 Generated Latest Changes for v2021-02-25 (Account Preferred Time Zone)
  Recurly/Resources/Account.cs
  Recurly/Resources/AccountCreate.cs
  Recurly/Resources/AccountPurchase.cs
  Recurly/Resources/AccountUpdate.cs
  Recurly/Resources/AddOn.cs
  Recurly/Resources/AddOnCreate.cs
  Recurly/Resources/AddOnUpdate.cs
  Recurly/Resources/Invoice.cs
  Recurly/Resources/SubscriptionAddOn.cs
  Recurly/Resources/SubscriptionAddOnCreate.cs
  Recurly/Resources/SubscriptionAddOnUpdate.cs
  Recurly/Resources/Usage.cs
  openapi/api.yaml
Labels: V4

#759 Add support for custom fields on charges
  Library/Adjustment.cs
  Test/PurchaseTest.cs
Labels: V2

#761 Generated Latest Changes for v2021-02-25 (Custom Fields on Line Items)
  Recurly/Constants.cs
  Recurly/Resources/LineItem.cs
  Recurly/Resources/LineItemCreate.cs
  openapi/api.yaml
Labels: V4

#762 Generated Latest Changes for v2019-10-10 (Custom Fields on Line Items)
  Recurly/Resources/LineItem.cs
  Recurly/Resources/LineItemCreate.cs
  openapi/api.yaml
Labels: V3

#760 Add Unit Tests for Custom Fields on Adjustments
  Library/Address.cs
  Library/ExternalResource.cs
  Library/InvoiceTemplate.cs
  Library/List/SubscriptionAddOnList.cs
  Test/AdjustmentTest.cs
  Test/InvoiceTest.cs
Labels: V2

#763 Add Tests for Invoices with Custom Fields on Adjustments
  Test/InvoiceTest.cs
  Test/List/InvoiceListTest.cs
Labels: V2

#758 Added DeclineCode to TransactionError
  Library/TransactionDeclineEnum.cs
  Library/TransactionError.cs
Labels: V2
