Repository recurly/recurly-client-dotnet, pull requests merged in 2023-04, with the labels that each got.

#779 Generated Latest Changes for v2021-02-25
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/ExternalCharge.cs
  Recurly/Resources/ExternalInvoice.cs
  openapi/api.yaml
Labels: V4

#781 Generated Latest Changes for v2021-02-25 (External Accounts)
  Recurly/Client.cs
  Recurly/IClient.cs
  Recurly/Resources/Account.cs
  Recurly/Resources/AccountCreate.cs
  Recurly/Resources/ExternalAccount.cs
  Recurly/Resources/ExternalAccountCreate.cs
  Recurly/Resources/ExternalAccountUpdate.cs
  openapi/api.yaml
Labels: V4

#783 Add UsedTaxService to Invoice response
  Library/Invoice.cs
  Test/Fixtures/invoices/mark_failed-200.xml
  Test/Fixtures/invoices/mark_successful-200.xml
  Test/Fixtures/invoices/show-200.xml
  Test/InvoiceTest.cs
Labels: V2

#784 Generated Latest Changes for v2019-10-10
  Recurly/Client.cs
  Recurly/Resources/BillingInfoCreate.cs
  Recurly/Resources/CustomFieldDefinition.cs
  Recurly/Resources/Invoice.cs
  openapi/api.yaml
Labels: V3

#785 Generated Latest Changes for v2021-02-25
  Recurly/Constants.cs
  Recurly/Resources/Invoice.cs
  openapi/api.yaml
Labels: V4
